acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),

]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y")
    comment = models.TextField()
    point = models.IntegerField(default=0)

    def getpic(self):
        if self.pic:
            return self.pic.url
        return"/media/no.png"

    

board/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likey")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey=models.ManyToManyField(User, blank=True related_name="likey")

    def __str__(self):
        return self.subject

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User

def chpass(request):
    cp = request.POST.get("cpass")
    np = request.POST.get("npass")
    if check_password(cp, u.password):
        np=request.POST.get("npass")
        u.set_password(np)
        u.save()
        return redirect("acc:login")
    return redirect("acc:update")
       


def update(request):
    if request.method == "POST":
        u = request.user
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lanme")
        pi = request.POST.get("upic")
        if pi:
            u.pic.delete()
            u.pic=pi
        u.comment, u.email, u.first_name, u.last_name = uc, ue, uf, ul
        u.save()
    return render(request, "acc/update.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lanme")
        pi = request.POST.get("upic")
       User.objects.create_user(username=un, password=up, comment=uc, email=ue, first_name=uf, last_name=ul, pic=pi)
        return redirect("acc:login")
    return render(request, "acc/singup.html")

def delete(request):
    cp = request.post.get("cpass")
    if check_passod(cp, u.password):
        u.pic.delete()
        u.delete()
        return redirect("acc:index")
    else:
        pass
   
    return redirect("acc:profile")

def profile(request):
    return render(request, "acc/profile.html")


def userlogout(request):
    logout(request)
    return render(request, "acc/index.html")


def userlogin(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u :
            login(request, u)
            return redirect("acc:index")
        else:
            pass
    return render(request, "acc/login.html")




def index(request):
    return render(request, "acc/index.html")

board/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'board/index.html')

templates/acc/base.html
 {% if user.is_authenticate %}
    <a href="{% url 'acc:index' %}" class="menu">HOME</a>
    <a href="{% url 'acc:profile' %}" class="menu">PROFILE</a>
    <a href="{% url 'acc:logut' %}" class="menu">LOGIN</a>

 {% else %}
    <a href="{% url 'acc:index' %}" class="menu">HOME</a>
    <a href="{% url 'acc:login' %}" class="menu">LOGIN</a>
    <a href="{% url. 'acc:signup' %}" class="menu">SIGNUP</a>
{% endif %}

<h6>접송중인 계정<b> {{ user }}</b></h6>

<hr>
<br><br>
{% block con %}

{% endblock %}

<style>
    .menu {
        text-decoration: none;
        font-size: 25px;
        color : black;
        font-weight: bold;
        margin-right: 30px;
    }

    .app{
        text-decoration: none;
        font-size: 25px;
        color : blue;
        font-weight: bold;
        margin-right: 30px;
    }

    .app:hover{
        color:black
    }
    .menu:hover{
        color : rgba(7, 73, 253, 0.863);
    }

</style>

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
자식
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}
    <h1>lOGIN PAGE</h1>
    <form>
        {% csrf_token %}
        <input type = "text" placeholder="INTPUT YOUR USERNAME" size="30" name="uname"><br><br>
        <input type = "password" placeholder="INTPUT YOUR PASSWORD" size="30" name="upass"><br><br>
        <button>로그인</button>
    </form>

{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <h1>PROFILE PAGE</h1>

    <img src="{{ user.getpic }}" width="250px"><br><br>

    <table>
        <tr>
            <th>USERNAME</th>
            <td><input type="text" value="{{user.username}}" disabled></td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td><input type="text" value="{{user.email}}" disabled></td>
        </tr>
        <tr>
            <th>LASTNAME</th>
            <td><input type="text" value="{{user.last_name}}" disabled></td>
        </tr>
        <tr>
            <th>FIRSTNAME</th>
            <td><input type="text" value="{{user.first_name}}" disabled></td>
        </tr>
        <tr>
            <td colspan="2"> <textarea cols="40" rows="5" disabled>{{user.comment}}</textarea> </td>
        </tr>
    </table>

    <br>
    <a href="{% url 'acc:'update' %}"><button>정보수정</button></a>

    <hr>
    <form method="post", action="{% url 'acc:delete' %}">
        {% csrf_token %}
        <h6>계정을 삭제하려면 현재 패스워드를 입력해주셔야 합니다</h6>
        <input type = "password" name = "cpass" placeholder="INPUT CURRENT PASSWORD" size="30">
        <Button>계정삭제</Button>
    </form>

    <br><br><br>
    <style>
        th, td{
            padding: 10px;
        }
    </style>

{% endblock %}

templates/acc/signup.html
<h1>PROFILE PAGE</h1>
<form>
    {% csrf_token %}
    <img src="{{ user.getpic }}" width="250px"><br><br>

    <table>
        <tr>
            <th>USERNAME</th>
            <td><input type="text" value="{{user.username}}" disabled></td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td><input type="text" value="{{user.email}}" disabled></td>
        </tr>
        <tr>
            <th>LASTNAME</th>
            <td><input type="text" value="{{user.last_name}}" disabled></td>
        </tr>
        <tr>
            <th>FIRSTNAME</th>
            <td><input type="text" value="{{user.first_name}}" disabled></td>
        </tr>
        <tr>
            <td colspan="2"> <textarea cols="40" rows="5" disabled>{{user.comment}}</textarea> </td>
        </tr>
    </table>
    <button>회원가입</button>
</form>

    <style>
        th, td{
            padding: 10px:
        }
    </style>

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <h1>UPDATE PAGE</h1>

    <form method="post>
    <table>
        {% csrf_token %}
        <tr>
            <th>USERNAME</th>
            <td><input type="text" name="uname" value="{{user.username}}" disabled></td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td><input type="text" value="{{ user.email }}" name="umail"></td>
        </tr>
        <tr>
            <th>LASTNAME</th>
            <td><input type="text" value="{{ user.last_name }} name="lname"></td>
        </tr>
        <tr>
            <th>FIRSTNAME</th>
            <td><input type="text" name="fname" value="{{ first_name }}></td>
        </tr>
        <tr>
            <td colspan="2"><input type="file" name="upic"> </td>
        </tr>
        <tr>
            <td colspan="2"> <b>COMMENT</b><br><textarea cols="40" rows="5" name="ucomm"></textarea> </td>
        </tr>
    </table>
</form>
    <button>정보수정</button>
   
    <hr>

    <form method="post">
        <h6>패스워드를 변경하려면 현재 비밀번호와 바꿀 비밀번호를 입력해주세요. <br>※ 변경 시 자동으로 로그아웃 됩니다!!</h6>
        <input type="password" placeholder="INPUT CURRENT PASSWORD" size="30">
        <input type="password" placeholder="INPUT NEW PASSWORD" size="30">
        <button>패스워드변경</button>
    </form>



    <style>
        th, td{
            padding: 10px;
        }
    </style>
{% endblock %}

templates/board/board.html
% extends 'base.html' %